server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shehani-wijetunga/microservices-config-store
          username: shehani-wijetunga
          password: AZBYcxdw123
          search-paths:
            - 'service-config/*service'

